//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChatSwitch.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WechatCache
    {
        public int Id { get; set; }
        public string Token { get; set; }
        public string Ticket { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    }
}
