//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wechat.WechatMessageHandlerSvc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WechatMessageHandlerSvc.IWechatSvc")]
    public interface IWechatSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWechatSvc/HandleEventMessage", ReplyAction="http://tempuri.org/IWechatSvc/HandleEventMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatBaseMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatTextMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatImageMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatEventMessage))]
        Wechat.WechatBaseMessage HandleEventMessage(Wechat.WechatEventMessage arg, string rawXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWechatSvc/HandleTextMessage", ReplyAction="http://tempuri.org/IWechatSvc/HandleTextMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatEventMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatBaseMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatImageMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatTextMessage))]
        Wechat.WechatBaseMessage HandleTextMessage(Wechat.WechatTextMessage arg, string rawXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWechatSvc/HandleImageMessage", ReplyAction="http://tempuri.org/IWechatSvc/HandleImageMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatEventMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatBaseMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatTextMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatImageMessage))]
        Wechat.WechatBaseMessage HandleImageMessage(Wechat.WechatImageMessage arg, string rawXml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWechatSvc/HandleUnknownMessage", ReplyAction="http://tempuri.org/IWechatSvc/HandleUnknownMessageResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatTextMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatImageMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Wechat.WechatEventMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Collections.Generic.List<object>))]
        Wechat.WechatBaseMessage HandleUnknownMessage(Wechat.WechatBaseMessage arg, string rawXml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWechatSvcChannel : Wechat.WechatMessageHandlerSvc.IWechatSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WechatSvcClient : System.ServiceModel.ClientBase<Wechat.WechatMessageHandlerSvc.IWechatSvc>, Wechat.WechatMessageHandlerSvc.IWechatSvc {
        
        public WechatSvcClient() {
        }
        
        public WechatSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WechatSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WechatSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WechatSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Wechat.WechatBaseMessage HandleEventMessage(Wechat.WechatEventMessage arg, string rawXml) {
            return base.Channel.HandleEventMessage(arg, rawXml);
        }
        
        public Wechat.WechatBaseMessage HandleTextMessage(Wechat.WechatTextMessage arg, string rawXml) {
            return base.Channel.HandleTextMessage(arg, rawXml);
        }
        
        public Wechat.WechatBaseMessage HandleImageMessage(Wechat.WechatImageMessage arg, string rawXml) {
            return base.Channel.HandleImageMessage(arg, rawXml);
        }
        
        public Wechat.WechatBaseMessage HandleUnknownMessage(Wechat.WechatBaseMessage arg, string rawXml) {
            return base.Channel.HandleUnknownMessage(arg, rawXml);
        }
    }
}
